HTTP 200 OK
Access-Control-Allow-Origin: *
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
Feature-Policy: payment 'self'
X-Recruiting: /#/jobs
Content-Type: application/json; charset=utf-8
Content-Length: 784
ETag: W/"310-RfcNI+rwg5kqntaQqjTYDiNiS+4"
Vary: Accept-Encoding
Date: Sat, 05 Sep 2026 18:34:57 GMT
Connection: keep-alive
Keep-Alive: timeout=5

{"authentication":{"token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJkYXRhIjp7ImlkIjoxLCJ1c2VybmFtZSI6IiIsImVtYWlsIjoiYWRtaW5AanVpY2Utc2gub3AiLCJwYXNzd29yZCI6IjAxOTIwMjNhN2JiZDczMjUwNTE2ZjA2OWRmMThiNTAwIiwicm9sZSI6ImFkbWluIiwiZGVsdXhlVG9rZW4iOiIiLCJsYXN0TG9naW5JcCI6IiIsInByb2ZpbGVJbWFnZSI6ImFzc2V0cy9wdWJsaWMvaW1hZ2VzL3VwbG9hZHMvZGVmYXVsdEFkbWluLnBuZyIsInRvdHBTZWNyZXQiOiIiLCJpc0FjdGl2ZSI6dHJ1ZSwiY3JlYXRlZEF0IjoiMjAyNi0wOS0wNSAxNzozMjozNi43MTIgKzAwOjAwIiwidXBkYXRlZEF0IjoiMjAyNi0wOS0wNSAxNzozMjozNi43MTIgKzAwOjAwIiwiZGVsZXRlZEF0IjpudWxsfSwiYmlkIjoxLCJpYXQiOjE3ODg2MzMyOTd9.Acf1J59Y8_CLLQHX3os0zcxkjV-mQ0SSXHI0JVAcsL2Pg5sYPmo5aXIMEmYjzqHlfszUU3DEg9H0_H8cUicf-LCm-RCUqu_AgQFvVWQqpiPe9RthWyyDsA6zOssckvIbmcK5oSn5lKzZkE-BiwWG9C_5u5lNce2HWY3z-yWWcCo","bid":1,"umail":"admin@juice-sh.op"}}