POST http://127.0.0.1:3000/api/BasketItems/
User-Agent: python-requests/2.34.2
Accept-Encoding: gzip, deflate
Accept: */*
Connection: keep-alive
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJkYXRhIjp7ImlkIjozNywidXNlcm5hbWUiOiIiLCJlbWFpbCI6Imlkb3ItZTZmODk0ZTNlY0BsYWIubG9jYWwiLCJwYXNzd29yZCI6ImZlYzgzNDM4YTEwNGViNTIzNDczYjNlMGZmZjdiNWFhIiwicm9sZSI6ImN1c3RvbWVyIiwiZGVsdXhlVG9rZW4iOiIiLCJsYXN0TG9naW5JcCI6IjAuMC4wLjAiLCJwcm9maWxlSW1hZ2UiOiIvYXNzZXRzL3B1YmxpYy9pbWFnZXMvdXBsb2Fkcy9kZWZhdWx0LnN2ZyIsInRvdHBTZWNyZXQiOiIiLCJpc0FjdGl2ZSI6dHJ1ZSwiY3JlYXRlZEF0IjoiMjAyNi0wOS0wNSAxODozNDo1Ny43MDUgKzAwOjAwIiwidXBkYXRlZEF0IjoiMjAyNi0wOS0wNSAxODozNDo1Ny43MDUgKzAwOjAwIiwiZGVsZXRlZEF0IjpudWxsfSwiYmlkIjoxNywiaWF0IjoxNzg4NjMzMjk4fQ.REtjdM2YT1d6I_OM47bg3ANKPY4Hqnd42WVa4dBEwjq4AtyG1q49-DnzvUA_dD7lWJicrX69KgZLJevw9CZHySe3Eg17PnonybchfYo5dYMxmdI0l7Ii2t0-05c-NR9pTbyebIZsoZH-_zEQt1oCBoMdaEWwMpMi380VT75FhmQ
Content-Length: 49
Content-Type: application/json

{"ProductId": 1, "BasketId": "17", "quantity": 2}